version: '3.7'
services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        environment:
          - cluster.name=dev-cluster
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=0.0.0.0
        ports:
          - '9200:9200'

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.0
        environment:
            - SERVER_HOST=0.0.0.0
        ports:
            - '5601:5601'
    
#    rabbitmq:
#      container_name: rabbitmq-elastic
#      image: rabbitmq:3-management
#      hostname: rabbitmq
#      ports:
#        - 15672:15672
#        - 5672:5672

networks: 
    default:
        name: elastic-kibana-rabbitmq-network
